migrateup:
	migrate -path migrations -database "postgres://postgres:Zbekxzz3@localhost:5432/order-service?sslmode=disable" up
migratedown:
	migrate -path migrations -database "postgres://postgres:Zbekxzz3@localhost:5432/order-service?sslmode=disable" down
run:
	@go run ./cmd/api